# Dependencies
markdown:         redcarpet
highlighter:      pygments


excerpt_separator: <!--more-->

# Permalinks
permalink:        pretty

# Site settings
title: '#EspaiSid'
email: rgil@oxygen.cat
description: '#EspaiSid és un projecte per compartir idees, dialogar sobre art i també inspirar i desenvolupar projectes de creació artística.'
baseurl:
url: "https://www.espaisid.com" 
twitter_username: freecates
github_username:  freecates
twitter:          artinpocket

sass:
 style: compressed

author:
  name:           'Ramon Gil'
  url:            https://twitter.com/freecates

# Build settings
markdown: kramdown

#Custom vars
portfoli-author:
 name: "#EspaiSid"
 url: http://www.espaisid.com/
organitza:
  artinpocket:
    description:  "Artinpocket - organitzadors d'#espaisid"
    logo: "artinpocket-organitzadors-barcelona-digital-art-footer.jpg"
    url: http://www.artinpocket.cat/
  sidpublicitat:
    description:  "SidPublicitat - organitzadores d'#espaisid"
    logo: "sid-publicitat-organitzadors-espaisid.jpg"
    url: http://www.sidpublicitat.com/

colabora:
  oxygen:
    description:  "Oxygen - Partner tecnològic d'#espaisid"
    logo: "oxygen-organitzadors-barcelona-digital-art-footer.jpg"
    url:  http://www.oxygen.cat/

sale-end: '2014-12-31T00:00:00+01:00'

bower_components: 
  baseurl: /bower_components/
